### ISSUE TITLE
前后端接口不一致

### ISSUE THREAD

**Issue by zhuima** [gozeon/oHelp-server#1]
看了下前端的审批提交页面的字段和后端的approval不一致，估计是上传代码的时候没有更新到最新的吧

**Comment by gozeon** [comment]
检查过了，字段没问题，那是`审批人`

**Comment by zhuima** [comment]
前端提交：
          this.axios
            .post('/approval/', {
              ...this.form,
              assigner: join(this.form.assigner, ','),
              content: JSON.stringify(pick(this.form, ['type', 'title', 'phone', 'time', 'reason'])),
            })

后端数据结构：
type Approval struct {
	CommonModel
	Title      string `gorm:"size:120;index" binding:"required" json:"title"`
	Content    string `gorm:"type:text"  binding:"required" json:"content"`
	Status     uint   `gorm:"index" json:"status" desc:"审评中 1、通过 2、驳回 3"`
	Approver   string `gorm:"size:25;index;not null"  binding:"required" json:"approver"`
	Assigner   string `gorm:"size:200" json:"assigner"`
	CreateUser string `gorm:"size:25;not null"  json:"create_user"`
}

字段对应不上呢
